[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emotion-cli"
version = "0.0.1"
dependencies = [
    "transformers",
    "torch",
]

[project.scripts]
emotion-cli = "emotion_cli_pkg.cli:main"