program: fine_tuning/train.py  # The path to your training script
method: bayes                # The search method (e.g., random, grid, bayes)
metric:
  name: eval/f1              # The metric you want to optimize (e.g., F1-score)
  goal: maximize             # Whether to maximize or minimize the metric
parameters:
  learning_rate:
    min: 0.00001
    max: 0.0001
  per_device_train_batch_size:
    values: [16, 32, 64]